# Generated by Django 5.2 on 2025-04-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_cardapplicationrequest_gettranscriptrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
