# Generated by Django 5.2 on 2025-04-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_talk_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='degree',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='job_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='linked_in',
            field=models.URLField(blank=True, null=True),
        ),
    ]
