# Generated by Django 5.2 on 2025-04-30 10:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_donatebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=Decimal('10.9254'), max_digits=9),
        ),
        migrations.AddField(
            model_name='userdata',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=Decimal('79.8380'), max_digits=9),
        ),
    ]
