# Generated by Django 5.2 on 2025-04-27 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('job_title', models.CharField(max_length=255)),
                ('job_company', models.CharField(max_length=255)),
                ('job_location', models.CharField(max_length=255)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.TextField()),
                ('short_bio', models.TextField()),
                ('topic', models.TextField()),
                ('datetime', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('extra_text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_is_approved', models.BooleanField(default=False)),
                ('roll_no', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('batch', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('in_job', models.BooleanField(default=False)),
                ('present_address', models.TextField()),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('higher_study_uni_name', models.CharField(blank=True, max_length=255, null=True)),
                ('higher_study_uni_address', models.CharField(blank=True, max_length=255, null=True)),
                ('higher_study_field', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
