# Generated by Django 5.2 on 2025-04-28 00:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardApplicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('First Application', 'First Application'), ('Card Lost', 'Card Lost')], max_length=50)),
                ('utr_transaction_number', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userdata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='GetTranscriptRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userdata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='GuestHouseBookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_room', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double')], max_length=10)),
                ('reason_of_visit', models.TextField()),
                ('datetime_in', models.DateTimeField()),
                ('datetime_out', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userdata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.userdata')),
            ],
        ),
    ]
